### ISSUE TITLE
Type error, can't figure it out.

### ISSUE THREAD

**Issue by Candy505** [kshitijofficial/Dgdrive3.0#4]
on executing  --  npx hardhat run --network localhost scripts/deploy.js

the error I encounter is --->

TypeError: no matching function (argument="key", value="deployed", code=INVALID_ARGUMENT, version=6.6.4)
 
at makeError (..\g_drive\node_modules\ethers\src.ts\utils\errors.ts:670:21)
    at assert (..\g_drive\node_modules\ethers\src.ts\utils\errors.ts:694:25)
    at assertArgument (..\g_drive\node_modules\ethers\src.ts\utils\errors.ts:706:5)
    at Interface.getFunctionName (..\g_drive\node_modules\ethers\src.ts\abi\interface.ts:542:23)
    at buildWrappedMethod (..\g_drive\node_modules\ethers\src.ts\contract\contract.ts:334:34)
    at BaseContract.getFunction (..\g_drive\node_modules\ethers\src.ts\contract\contract.ts:859:22)
    at Object.get (..\g_drive\node_modules\ethers\src.ts\contract\contract.ts:757:39)
    at main (..\g_drive\scripts\deploy.js:7:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'INVALID_ARGUMENT',
  argument: 'key',
  value: 'deployed'
}

**Comment by kshitijofficial** [comment]
I have now updated the README. Please read the Usage section.
